# **Norwegian News Articles**
Project for TDT4310

By: Malin Haugland Høli

## News Framing

### *Imports*

In [1]:
import pandas as pd
import spacy
from pathlib import Path

from transformers import pipeline
from tqdm import tqdm
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

c:\NTNU\V26\TDT4310\Project\exploring-norwegian-news-sources\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### *Import dataset*

In [2]:
df = pd.read_parquet("../combined-2019.parquet")
df.head(3)

,file,url,source,date,author,gender,class1,class2,language,title,ingress,text,word_count,sentence_count
0,VG-20190101-16-personer-fikk-oye.xml,http://www.vg.no/nyheter/innenriks/i/jPyoyb/16...,VG,2019-01-01 09:12,Halvor Bjørntvedt,Male,"nyheter,innenriks",None,Bokmål,16 personer fikk øyeskader av fyrverkeri,Fem fikk alvorlige skader etter gårsdagens nyt...,"Tallene, som viser øyeskader på landsbasis, vi...",209,13
1,VG-20190101-47-plass-for-sundby-.xml,http://www.vg.no/sport/langrenn/i/3j8ra0/47-pl...,VG,2019-01-01 10:19,"Nils Mangelrød, Jostein Overvik",Male,"sport,langrenn",None,Bokmål,47. plass for Sundby - nekter å prate etter ne...,VAL MÜSTAIR (VG) Martin Johnsrud nektet å prat...,Den tidligere Tour de Ski-vinneren var svært l...,533,42
2,VG-20190101-94-drap-pa-journalis.xml,http://www.vg.no/nyheter/utenriks/i/J19kWP/94-...,VG,2019-01-01 21:37,Mikal Hem,Male,"nyheter,utenriks","Drap, Ytringsfrihet, Journalistikk, Korrupsjon...",Bokmål,94 drap på journalister i 2018: Skal ha blitt ...,Antall drepte journalister i Vesten har skutt ...,25. februar ble Jan Kuciak og hans forlovede M...,539,44

---
### *Sample 1000 articles from each source*

In [3]:
samples = []
for source in df["source"].unique():
    sample = df[df["source"] == source].sample(1000, random_state=42)
    print(f"Sampled {len(sample)} articles from {source}")
    samples.append(sample)

sample_df = pd.concat(samples)  # original indexes preserved
assert len(set(sample_df.index)) == len(sample_df)  # check for duplicates

Sampled 1000 articles from VG
Sampled 1000 articles from AA
Sampled 1000 articles from AP
Sampled 1000 articles from BT
Sampled 1000 articles from DA
Sampled 1000 articles from DN
Sampled 1000 articles from DB
Sampled 1000 articles from FV
Sampled 1000 articles from NL
Sampled 1000 articles from SA

---
### *POS and Dependency Tags*

In [4]:
nlp = spacy.load("nb_core_news_lg", disable=["ner"])

In [5]:
def analyze_article(text):
    """
    Analyze the article text to extract linguistic features.
    Returns a dictionary with verb ratio, subject ratio, passive voice ratio, and passive of verbs ratio.
    """
    doc = nlp(text)

    verbs = []
    subjects = []
    passive_count = 0

    for token in doc:
        if token.pos_ == "VERB":
            verbs.append(token.lemma_.lower())

        if token.dep_ in ("nsubj", "nsubj:pass"):
            subjects.append(token.lemma_.lower())

        if token.dep_ == "aux:pass":
            passive_count += 1

    token_count = len(doc)

    return {
        "verb_ratio": len(verbs) / token_count if token_count > 0 else 0,
        "subject_ratio": len(subjects) / token_count if token_count > 0 else 0,
        "passive_ratio": passive_count / token_count if token_count > 0 else 0,
        "passive_of_verbs": passive_count / len(verbs) if len(verbs) > 0 else 0,
    }

In [6]:
analysis_results = []

for idx, row in tqdm(sample_df.iterrows(), total=sample_df.shape[0]):
    analysis_results.append(analyze_article(row["text"]))

analysis_df = pd.DataFrame(analysis_results)
analysis_df.index = sample_df.index  # align indexes for merging
analysis_df = pd.merge(sample_df, analysis_df, left_index=True, right_index=True)
analysis_df.head(3)

100%|██████████| 10000/10000 [11:46<00:00, 14.16it/s]

,file,url,source,date,author,gender,class1,class2,language,title,ingress,text,word_count,sentence_count,verb_ratio,subject_ratio,passive_ratio,passive_of_verbs
5643,VG-20190423-ekstra-bladet-danske.xml,http://www.vg.no/nyheter/utenriks/i/awOaE7/eks...,VG,2019-04-23 12:57,"Ingvill Dybfest Dahl, Ingeborg Huse Amundsen, ...",Female,"nyheter,utenriks",None,Bokmål,Ekstra Bladet: Danske Anders Holch Povlsen på ...,Den danske klesmilliardæren som mistet tre av ...,"Det skriver danske Ekstra Bladet, som siterer ...",439,27,0.099804,0.088063,0.007828,0.078431
6808,VG-20190516-sarah-jessica-parker.xml,http://www.vg.no/rampelys/film/i/rA5exK/sarah-...,VG,2019-05-16 07:37,Catherine Gonsholt Ighanian,Female,"rampelys,film",None,Bokmål,Sarah Jessica Parker raser mot ukeblad – viser...,Ukebladet som sier at de jobber med en sak om ...,Den tidligere «Sex og singelliv»-stjernen har ...,435,26,0.095785,0.086207,0.001916,0.020000
4593,VG-20190401-rotteracet-om-champi.xml,http://www.vg.no/sport/fotball/i/opEPLm/rotter...,VG,2019-04-01 10:20,Ole Kristian Strøm,Male,"sport,fotball",None,Bokmål,Rotteracet om Champions League-plass: – Det er...,Mandag kveld har Arsenal sjansen til å presse ...,Mandagens oddstips finner du her\n– Jeg våger ...,611,45,0.098571,0.092857,0.004286,0.043478

#### *Linguistic features by source*

In [7]:
source_stats = analysis_df.groupby("source").agg({
    "passive_ratio": "mean",
    "subject_ratio": "mean",
    "verb_ratio": "mean",
    "passive_of_verbs": "mean"
})
print(source_stats)

        passive_ratio  subject_ratio  verb_ratio  passive_of_verbs
source
AA           0.005571       0.094068    0.102430          0.053794
AP           0.005272       0.093220    0.102769          0.051138
BT           0.004702       0.093543    0.103314          0.045172
DA           0.005144       0.092860    0.103919          0.049007
DB           0.004786       0.094752    0.104951          0.045786
DN           0.003562       0.090372    0.100508          0.035075
FV           0.004851       0.092375    0.102397          0.047441
NL           0.005889       0.091954    0.101774          0.056576
SA           0.004196       0.091370    0.101193          0.040898
VG           0.005370       0.097687    0.107851          0.050151

---
### *Sentiment analysis*

In [8]:
pipe = pipeline(
    "text-classification",
    model="malinhauglandh/norec-sentiment-norbert3-small",
    trust_remote_code=True
)

Loading weights: 100%|██████████| 128/128 [00:00<00:00, 1677.78it/s]

In [10]:
def chunk_list(lst, size):
    for i in range(0, len(lst), size):
        yield lst[i:i + size]

texts = sample_df["text"].tolist()

outputs = []

for chunk in tqdm(chunk_list(texts, 20), total=(len(texts) + 19) // 20):  # chunk size = 20
    preds = pipe(
        chunk,
        batch_size=4,
        truncation=True,
        max_length=256
    )
    outputs.extend(preds)

100%|██████████| 500/500 [39:38<00:00,  4.76s/it]

In [11]:
analysis_df["label"] = [o["label"] for o in outputs]
analysis_df["score"] = [o["score"] for o in outputs]
analysis_df.head(3)

,file,url,source,date,author,gender,class1,class2,language,title,ingress,text,word_count,sentence_count,verb_ratio,subject_ratio,passive_ratio,passive_of_verbs,label,score
5643,VG-20190423-ekstra-bladet-danske.xml,http://www.vg.no/nyheter/utenriks/i/awOaE7/eks...,VG,2019-04-23 12:57,"Ingvill Dybfest Dahl, Ingeborg Huse Amundsen, ...",Female,"nyheter,utenriks",None,Bokmål,Ekstra Bladet: Danske Anders Holch Povlsen på ...,Den danske klesmilliardæren som mistet tre av ...,"Det skriver danske Ekstra Bladet, som siterer ...",439,27,0.099804,0.088063,0.007828,0.078431,neutral,0.540266
6808,VG-20190516-sarah-jessica-parker.xml,http://www.vg.no/rampelys/film/i/rA5exK/sarah-...,VG,2019-05-16 07:37,Catherine Gonsholt Ighanian,Female,"rampelys,film",None,Bokmål,Sarah Jessica Parker raser mot ukeblad – viser...,Ukebladet som sier at de jobber med en sak om ...,Den tidligere «Sex og singelliv»-stjernen har ...,435,26,0.095785,0.086207,0.001916,0.020000,neutral,0.640248
4593,VG-20190401-rotteracet-om-champi.xml,http://www.vg.no/sport/fotball/i/opEPLm/rotter...,VG,2019-04-01 10:20,Ole Kristian Strøm,Male,"sport,fotball",None,Bokmål,Rotteracet om Champions League-plass: – Det er...,Mandag kveld har Arsenal sjansen til å presse ...,Mandagens oddstips finner du her\n– Jeg våger ...,611,45,0.098571,0.092857,0.004286,0.043478,neutral,0.488746

In [12]:
analysis_df["label"].value_counts()

label
neutral     7400
positive    2368
negative     232
Name: count, dtype: int64

### *Print labels*

In [13]:
# print 3 examples of each label
for label in analysis_df["label"].unique():
    print(f"\n--- {label.upper()} EXAMPLES ---")
    examples = analysis_df[analysis_df["label"] == label].head(3)
    for idx, row in examples.iterrows():
        print(f"\nExample {idx} (score: {row['score']:.4f}):")
        print(row["text"][:2000])

--- NEUTRAL EXAMPLES ---

Example 5643 (score: 0.5403):
Det skriver danske Ekstra Bladet, som siterer kilder ved akuttmottaket.
– Et av familiemedlemmene var skadet, men er nå utskrevet fra sykehus, bekrefter Danmarks ambassadør i India, Peter Taksøe-Jensen, overfor VG.
På National Hospital of Sri Lanka bekrefter flere kilder at en fra Holch Povlsen-familien var såret i angrepet på luksushotellet Shangri-La og innlagt. En medarbeider ved akuttmottaket opplyser at det var snakk om en voksen dansk mann.
Bakgrunn: Dette vet vi om angrepene
Den 46 år gamle Bestseller-milliardæren og kona Anne Holch Povlsen (40) var på påskeferie sammen med barna på Sri Lanka, da landet i Det indiske hav ble rammet av åtte eksplosjoner søndag.
Angrepene har så langt kostet 321 mennesker livet, og antall døde og skadede fortsetter å stige. Tre av barna til det danske ekteparet var blant de drepte.
Torsdag skal det etter planen holdes et fakkeltog i Stavdrup i Danmark, hvor Bestseller-familien bor. Dette blir arrangert for å vise medfølelse til familien.
Holch Povlsen har bedt om fred i sorgen.
Les mer: Den danske milliardærens liv
Anders og Anne Holch Povlsen er foreldre til de fire barna Alma, Astrid, Agnes og Alfred. Ifølge Ekstra Bladet er familiens fire barn er 5, 10, 12 og 15 år gamle. Det er ikke bekreftet hvem av barna som ble drept i angrepene.
– Vi støtter den danske familien som mistet tre av sine kjære, forteller ambassadør Taksøe-Jensen til VG på telefon fra den srilankiske hovedstaden Colombo.
Han har reist fra New Delhi til Colombo for å håndtere situasjonen. Danmark har ingen egen ambassade på Sri Lanka, og samarbeider derfor tett med den norske ambassaden i landet.
– Jeg kan ikke si så mye om hvordan vi bistår familien. Men jeg kan si at de forlot landet på mandag. Vi vil hjelpe dem med å få kroppene hjem til Danmark, sier Taksøe-Jensen.
I tillegg til ambassadøren har Danmark sendt et spesialistteam til Colombo bestående av rettsmedisinere som skal bidra til å identifisere de avdøde, sikkerhetsfolk som skal bistå i etterforskni

Example 6808 (score: 0.6402):
Den tidligere «Sex og singelliv»-stjernen har nemlig gått til det uvanlige skrittet å vise frem henvendelsen fra ukebladet for hele verden.
Parker, som har 5,4 millioner følgere på Instagram, skriver at det amerikanske tabloidmagasinet National Enquirer «nok en gang» dikter opp historier om henne og skuespillerektemannen.
«Etter nøye vurdering har jeg bestemt å vise frem et typisk brev om «granskingen» til disse folkene», skriver Parker under et bilde av den aktuelle e-posten.
«Som om sannheten eller enhver respons fra enten min talsperson eller meg ville ha noe å si for saken de truer med å «rapportere», fortsetter hun.
I brevet, som angivelig er fra omstridte National Enquirer, står det at bladet jobber med en sak etter at Parker og Broderick skal ha blitt avbildet mens de sto og skrek til hverandre på gaten. Ifølge bladet skal en kilde ha forklart at krangelen startet over en middag på en restaurant, og at den senere utartet ute på gaten.
Den påståtte krangelen skal ha handlet om hvor mye tid Broderick tilbringer i London. Kjendisparet selv har sin faste base i New York, men Broderick er for tiden aktuell på teaterscenen på West End i «The Starry Messenger».
National Enquirer gjør et nummer av at den angivelige episoden skal ha funnet sted få dager før stjerneparets 22 års bryllupsdag – 19. mai.
Henvendelsen fra bladet rundes av med at Parkers representanter har en frist til dagen derpå med å kommentere saken.
Det får Hollywood -stjernen til å se rødt.
«Det samme usanne, uverdige oppspinnet», skriver hun.
Parker hevder at National Enquirer gjør «sitt årlige beste» for å fabrikkere løgner for å ødelegge dagene for dem, «i år fire deilige dager med min mann i London».
«Det var ingen skrikende krangel hverken på noen restaurant eller gate. Ikke var det noen konfrontasjon om tiden han tilbringer i London heller. Barna og jeg er enormt stolte over den jobben han gjør», skriver hun videre.
Tidligere: Sarah Jessica Parker var redd for sosiale medier
Parker og Broderick

Example 4593 (score: 0.4887):
Mandagens oddstips finner du her
– Jeg våger ikke å spekulere i hvem som er på plass 3,4,5 og 6 når sesongen er over. Det eneste jeg vet er at det er fire klubber som folder hendene og håper på at de er topp 4 etter 38 seriekamper, fastslår Viasat-kommentator Roar Stokke.
Før mandagens kamp mellom Arsenal og Newcastle er det ekstremt jevnt på tabellen:
3. Tottenham 31 kamper-61 poeng.
4. Manchester United 31 kamper – 61 poeng.
5. Arsenal 30 kamper – 60 poeng.
6. Chelsea 31 kamper – 60 poeng.
For Arsenal er seier over Newcastle mandag kveld ekstremt viktig.
– Arsène Wenger ble ledd av og litt latterliggjort da han sa at topp fire i Premier League var en premie i seg selv. Kloke Wenger hadde helt rett, mener Stokke.
– Penger, status og sportslige utfordringer gjør Champions League til et turneringsformat som de største klubbene – og de beste spillerne – vil delta i hvert år. Jobben med å skaffe nye spillere til klubbene er betydelig enklere om man er topp fire.
Onsdag er det Vikinglotto: 56 mill. kroner
Roar Stokke peker på at det er to klubber som har skilt seg ut i Premier League.
– Denne sesongen er det kanskje viktigere enn noen gang, fordi det er fire klubber bak City og Liverpool som har tenkt å utjevne forspranget og handle spillere til sommeren.
– Hvem som blir nummer tre og fire er ren bingo å spekulere i. Kampprogram, skader på viktige spillere, karantene og lignende vil spille inn, mener Roar Stokke.
Han viser også til kampprogrammet, både i Premier League og Europa:
– Tottenham skal ut i tre tøffe kamper mot suverene Manchester City, inkludert Champions League. United får to kamper som stjeler oppmerksomhet mot Lionel Messi og Barcelona. Chelsea skal møte både Liverpool og Manchester United borte og Arsenal får to tøffe kamper mot Napoli i Europa League.
Stokke spør seg også:
– Kan ny stadion gi Spurs drahjelp og en ekstra fordel de siste kampene?
Arsenal tok en sterk seier over Manchester United før landslagspausen og har vunnet fire av sine fem siste Pre

--- POSITIVE EXAMPLES ---

Example 766 (score: 0.4594):
Tidligere har helseminister Bent Høie stilt som krav til norske sykehus at ventetiden ikke skal være mer enn 50 dager innen 2021 for behandling innen somatikk, psykisk helsevern og rusbehandling.
Nå skjerper han kravene ytterligere, og ber sykehusene redusere ventetiden ytterligere for psykisk helsevern og rusbehandling.
Høie sier han særlig er opptatt av å få ned ventetidene for barn og unge i psykisk helsevern.
– De må få hjelp før problemene vokser seg store. Hvis vi klarer å hjelpe barn og unge tidlig, vil det ha stor betydning for dem for resten av livet, sier han.
Han mener ventetiden for barn og unge med psykiske helseutfordringer er altfor lang i dag:
– Jeg er bekymret for at ventetiden er så lang som i dag. For barn og unge som har så alvorlige psykiske helseutfordringer at de må få hjelp av spesialisthelsetjenesten vet vi at ventetiden går utover muligheten til å delta i skolen og være med venner. Tiden går fortere når man er ung, og noen måneder borte fra skolen kan være vanskelige å ta igjen, sier han.
Tirsdag holder Høie sin årlige sykehustale, hvor han presenterer sine krav og forventninger til helseregionene for det kommende året:
Innen 2019 skal gjennomsnittlig ventetid være:
* Lavere enn 40 dager for psykisk helsevern for barn og unge. I dag er gjennomsnittlig ventetid 50 dager.
* Lavere enn 45 dager for psykisk helsevern for voksne. I dag er gjennomsnittlig ventetid 47 dager.
* Lavere enn 35 dager for tverrfaglig spesialisert rusbehandling (TSB).
Innen 2021 skal gjennomsnittlig ventetid reduseres ytterligere, til:
* Lavere enn 35 dager for psykisk helsevern for barn og unge.
* Lavere enn 40 dager for psykisk helsevern for voksne.
* Lavere enn 30 dager for tverrfaglig spesialisert rusbehandling (TSB).
I dag er ventetiden i psykisk helsevern 47 dager for voksne, og 50 dager for barn. Gjennomsnittlig ventetid for TSB, tverrfaglig spesialisert rusbehandling, er i dag på 35 dager.
I perioden 2013 til 2. tertial i 2018 ble ventetiden for somatikk, psykis

Example 4046 (score: 0.7172):
– Vi i regjeringen må vise handlekraft. Fra og med i dag blir det endringer: Regjeringen lover å doble budsjettet til klimabistand. Vi lover å stoppe all oljeleting, og 1.juni 2032 stenger vi kranen og stopper all oljeproduksjon i Norge, sa han fra scenen.
Slik åpnet mannen som utga seg for å være utviklingsminister Dag Inge Ulstein, sin tale til klimastreikerne.
Men det var altså ikke statsråden som stod på scenen. Det var nemlig komiker Thomas Teige. Tidligere har han blant annet lurt VG til å tro at han var utviklingsministeren.
Jubelen fra fra de flere tusen unge var ellevill, og ble ikke mindre da han lovet null fravær:
– Ingen skal få fravær for å være her i dag. Det garanterer jeg på vegne av regjeringen, sa komikeren.
– Når vi kjemper slike kamper betyr fravær null og niks. Var det noen som maset om fravær da nordmenn bekjempet nazisme? Og hvem førte fravær for de som rev ned Berlinermuren?
Komikeren, som utga seg for å være statsråden, beklaget videre at statsminister Erna Solberg ikke kunne være tilstede.
– Skulle noen likevel få problemer med fravær, oppfordrer jeg alle til å sende en e-post til Statsministerens kontor, sa han og leste opp en e-postadresse til SMKs postmottak.
Dobbeltgjenger-trøbbel for KrF-Ulstein – kom ikke inn til ny minister-jobb i UD
– Hvis dere sender en e-post til dem vil alle få gyldig fraværsbevis tilbake, sa han.
Etter stuntet var komikeren klar på at stuntet var i samarbeid med Natur og Ungdom.
– Her er intensjonen vår klokkeklar. Vi sier det regjeringen burde ha sagt for fem til ti år siden. Vår intensjon her er å gjøre det vanskelig for dem å trekke seg på disse helt grunnleggende kravene, sa komikeren til VGTV etter talen.
Prosjektleder for NRKs satireprogram Stig Morten Lorentzen Waage, mener stuntet er positivt, fordi det vil legge et press på politikerne.
– Jeg tenker at det var et morsomt stunt. Jeg tipper at ungdommene kanskje blir litt lei seg når de skjønner at dette var en tulleminister, men i det store bildet var de

Example 6118 (score: 0.6888):
Hauglie legger frem tall som viser at sysselsettingen økte i 331 av 371 kommuner i fjor.
Her kan du finne utviklingen i din og landets kommuner:
– Tallene underbygger at vår regjering er den beste regjeringen for arbeidsfolk flest.
– Du sier det bare for å provosere før 1. mai?
– Nei, jeg sier det fordi jeg mener det. Jeg har en stabel med statistikk som kan dokumentere at folk flest har fått det bedre under vår regjering enn under den rødgrønne.
– Hvordan?
– Ved at vår politikk bidrar til at flere arbeidsfolk har fått en trygg jobb å gå til. Ledigheten er lavere enn på ti år, arbeidslivskriminaliteten går ned og vi har liberalisert arbeidstidsbestemmelsene slik at det skal være lettere for arbeidsfolk å kombinere arbeid og familieliv. Regelverket for varsling er også styrket, sier hun og fortsetter:
– Så har en vanlig familie fått 10.000 kroner i skattelette under vår regjering.
– Og de rikeste over 300.000 kroner: Eksperter sier skattelette ikke har gitt flere arbeidsplasser?
– Anslag fra Finansdepartementet viser at skattelette vil støtte opp under vekstevnen i fastlandsøkonomien, ved å stimulere til at investeringer og arbeidstilbud øker over tid. Vi ønsker å gjøre det mer lønnsomt å skape jobber og gi folk mer å rutte med.
– Det kan hevdes at mye av veksten i 2018 skyldes at økonomien har snudd etter oljesmellen?
– Vi fikk skylden da ledigheten økte og det gikk dårlig – og bør kunne få litt av æren for å ha påvirket med tiltak som gjør at det nå går bedre.
– Opposisjonen vil si at dere har bidratt med skattelette først og fremst til de rike og ikke nok for å få flere heltidsstillinger og mindre sosial dumping på arbeidsplassene?
– Vi kan dokumentere at ledigheten går ned og at andelen som jobber heltid har gått opp. Skattelette treffer folk flest: Arbeidsfolk sitter igjen med mer av sine egne inntekter. Og vi kan dokumentere at flere useriøse arbeidsgivere blir tatt og at det i dag et tryggere på norske arbeidsplasser.
Hauglie bruke også tallene til et frontala

--- NEGATIVE EXAMPLES ---

Example 1197 (score: 0.8707):
THRILLER/DRAMA
«Destroyer»
USA. 15 år. Regi: Karyn Kusama.
Med: Nicole Kidman, Sebastian Stan, Scoot McNairy.
Det er nesten blitt en egen sjanger. «Vi de-glamoriserer en av verdens vakreste kvinner og vinner Oscar fordi vi er så fryktløse Charlize Theron i « Monster » (2003) og – ja visst – Nicole Kidman som Virginia Woolf i « The Hours » (2002).
Det blir i alle fall publisitet av det. Vi er ikke bedre mennesker enn at vi elsker å se vakre personer i mindre heldig lys. Men når dette grepet blir det eneste poenget med et kulturprodukt, blir det stusslig. Det er dette som har skjedd med «Destroyer».
Kidman, som politikvinnen Erin Bell, har røde ringer rundt øynene, knappenålspupiller og leverflekker på hendene. Hun er avmagret av fyll, og overnatter som regel i bilen.
Bell er forbitret, og det av brukbare årsaker. For 17 år siden var hun del av en undercover duo som jobbet for FBI, og som infiltrerte en bankranerbande – med katastrofale resultater.
Uskyldige mennesker døde. Skyldige mennesker gikk fri. Nå som gjenglederen fra den gang, Silas ( Toby Kebbell ), er tilbake i Los Angeles, er Erin rimelig nok besatt av hevntanker.
Bell er villig til å gå langt for å nøste inn sin nemesis. Inkludert å ta loven i egne hender, kompromittere seg selv og onanere en døende mann.
Historien utspiller seg på to tidsplan. Den gang, da Bell fremdeles var sjokkerende vakker, især til hardbarket yrkeskriminell å være, og gradvis ble forelsket i FBI-partneren sin, Chris ( Stan ). Og nå, nå som hun er et knust menneske med lite å tape, inkludert en ulykkelig datter som ikke elsker henne.
Filmanmeldelse: Prinsesse-pølsevev
Jeg kan ikke huske å ha sett den dyktige Kidman mindre overbevisende enn her. Skuespillerens distanserte, eksepsjonelle stil er en dårlig match for begge utgavene av Erin. Som ung agent skriker hun «spaner!» lang vei. Som lidende vrak er hun monoton, nesten latterlig. Det var nok ikke meningen.
Regissør Kusama forsøker å melke det trøblete mor-og datterforholdet for alt

Example 509 (score: 0.9286):
Denne måneden får dokumentarfilmen «Leaving Neverland» premiere på Sundance-festivalen.
Filmens synopsis lover «opprivende intervjuer» med de nå voksne mennene og deres familier, og skal etter eget utsagn vise hvordan en aktet kunstner kan utnytte sin kjendismakt overfor «starstruck» barn og deres foreldre.
Boet etter Michael Jackson har kommet med en uttalelse om filmen til TMZ .
– Dette er nok en uhyggelig produksjon i et vanvittig og patetisk forsøk på å utnytte og tjene penger på Michael Jackson. Denne såkalte dokumentaren er bare nok et oppkok av utdaterte og tilbakeviste påstander. Det er uforståelig at en respektert filmskaper vil involvere seg i et slikt prosjekt.
Filmens produsent, Dan Reed, har tidligere fått BAFTA-pris for dokumentaren «The Paedophile Hunter».
Britiske Channel 4 og amerikanske HBO har bekreftet at de viser den fire timer lange dokumentaren til våren.
Hvem de to påståtte overgrepsofrene er, er ikke kjent. TMZ mener imidlertid det er snakk om Wade Robson og James Safechuck, fordi Jackson-boet påpeker at «begge forklarte under ed at Michael aldri gjorde noe upassende overfor dem».
Neverland var en stor California-ranch med egen fornøyelsespark, hvor Jackson holdt hus fra 1988 til 2003.
I 2003 ble den ransaket av politiet, i forbindelse med en sak der en 13-åring anklaget Jackson for å ha misbrukt ham. Jackson ble frikjent i 2005.
Kommende sommer er det ti år siden popikonet døde av en overdose sovemedisin.

Example 1199 (score: 0.9019):
– Ber dere sammen?
Det spørsmålet stilte Fredrik Solvang Ropstad etter at han hadde fått konstatert at ministeren, hans statssekretær Julian Farner-Calvert og personlig sekretær Elisabeth Løland tilhører samme menighet, Oslo Misjonskirke.
– Spørsmålet burde ikke vært stilt. Det virker umotivert og bidrar bare til å tro at jeg her er ute etter kristenmannsblod. Grunnen til at jeg stilte spørsmålet var for å finne ut hvor tette og nære venner de er. Men det fungerte ikke, sier Fredrik Solvang til VG.
Reaksjonene lot da heller ikke vente på seg.
«Noen som sender mail og signerer med navn og postnummer mener jeg er en skam som bør tas av skjermen», skriver Fredrik Solvang på Facebook .
Han presiserer at han ikke er spesielt personlig engasjert i temaene han tok opp med Ropstad.
«Jeg prøver å spørre om det som er politisk og journalistisk interessant. Og i så måte angrer jeg på at jeg spurte om bønn, det var unødvendig», skriver Solvang videre.
Han forteller til VG at han har fått et tyvetalls «sinte» mailer etter intervjuet.
– Jeg ser av flere av tilbakemeldingene at intervjuet oppfattes som om jeg var ute etter å snevre inn rommet for hva det er mulig å mene og tro. Men det er aldeles ikke slik det er. Jeg forsøker på det stikk motsatte ved å forsøke å få han til å snakke fritt og ubesværet om de vanskelige dilemmaene han og partiet står i, og at det kan åpne rommet for hva det er mulig å snakke om, sier Solvang til VG.
Barne- og familieministeren reagerer imidlertid ikke negativt på «Debatten»-intervjuet:
«Fredrik Solvang er en journalist som jeg respekterer. Som politiker får jeg mange ulike spørsmål, og jeg reagerte ikke på at han spurte om bønn», sier Kjell Ingolf Ropstad (KrF) via sin pressekontakt i til VG.

In [14]:
# print 10 examples of each label with highest confidence
for label in analysis_df["label"].unique():
    print(f"\n--- {label.upper()} HIGH CONFIDENCE EXAMPLES ---")
    examples = analysis_df[analysis_df["label"] == label].sort_values("score", ascending=False).head(10)
    for idx, row in examples.iterrows():
        print(f"\nExample {idx} (score: {row['score']:.4f}):")
        print(row["text"][:2000])

--- NEUTRAL HIGH CONFIDENCE EXAMPLES ---

Example 55565 (score: 0.9929):
4
TV-drama
«Skitten snø»
NRK.no, premiere 31. oktober
En ungdomsserie som tar opp voldtekt, moralpoliti og skamkulturen som preger deler av et innvandrermiljø er ikke dagligdagse saker på NRK. «Skitten snø» byr på tematikken, i formm av dramaserien basert på boka til Mahmona Khan som kom for åtte år siden. «Skitten snø» var en kritikerrost ungdomsroman, omtalt som «en solid skjønnlitteratur debut» i denne avisen. TV-versjonen skal først og fremst være en spenningshistorie for unge seere som berører overgrep, vennskap, det å være offer for et overgrep, men enda viktigere det å ta tilbake kontroll over eget liv. Men selv om serien kommer med plakaten «for 15 år pluss» har «Skitten snø» også ambisjon om å nå målgruppas foreldre, å skape refleksjon og gi i innblikk i et samfunnsproblem som trenger oppmerksomhet.
Det er unge innvandrerjenter som har hovedrollen, men «Skitten snø» byr også en nedpå, flersidig skildring av folk i et samfunn de fleste av oss står utenfor, et norsk-pakistansk miljø i hovedstaden.
Mer ungdomsdrama: Velment og overtydelig i NRK-serien «18»
TV-versjonen av Khans bok er blitt en noe omskrevet krim i åtte episoder, som slippes i to og to episoder på tirsdager og torsdager de neste to ukene. Hovedperson er fortsatt tenåringsjenta Sumera, levende og godt spilt av Kamalpreet Kaur. Sumera er en livsglad, pliktoppfyllende jente som går siste år på videregående. Hun er fra en familie av den mer liberale, åpne sorten – i den betydning at foreldrene lar henne jobbe på Burger King på senteret etter skolen, selv om det innebærer at hun kommer seint hjem.
Dette er nok til at det norskpakistanske moralpolitiet i området reagerer, gjengen av unge og gamle menn som mener jenter skal «sette hjem og familie» først, som en av dem sier det. Kort sagt, være hjemme og holde kjeft. I dette miljøet skal ikke jenter omgås menn de ikke er gift med. Punktum. Jenter som gjør opposisjon, risikerer å bli sendt «hjem» til Pakistan. Skildringen av et menneskesyn av den typen

Example 4475 (score: 0.9895):
Så er det en mor med en krevende jobb som fortsatte på høygir hjemme. – Eg vart litt ufyseleg, rett og slett, sier kvinnen til Anne Gunn Halvorsen som har skrevet denne boken om stress.
Bokideen er usedvanlig god, for stress er noe enhver kan kjenne og preges av, og er et tema mange er opptatt av.
Lest? Din sønns nye sexleksikon - terningkast 5 til svensk sexbok
Anne Gunn Halvorsen hadde stor suksess med boken fra to år tilbake, «Livet og korleis leve det» - en håndbok om livet og hvordan leve det. Nå følger hun opp med temaet stress. Stress er definitivt en del av livet, så det er ikke uventet at Halvorsen ville gjøre et dypdykk i noe som preger mange så sterkt.
Les intervuet: Slik kan du unngå å bli sur, sliten og skilt
Men konseptet denne gang framstår ikke like gjennomført og vellykket som håndboken om livet selv. Foreliggende bok om stress har nærmest reportasjens form og er i partier skrevet i en litt for slentrende stil. Her er intervjuer med flere fagfolk og enkeltpersoner som har erfart stress, har råd og som deler.
Halvorsen forteller godt og har funnet mange gode og talende historier, men det irriterer at forfatteren ikke viser en tydeligere plan for hva hun tenker å gjøre i boken. De menneskene hun løfter fram, hvordan fant hun dem, hvorfor valgte hun dem? Det blir litt mye løsvekt, og denne leser tenker at hun kunne brukt fagekspertisen mer systematisk og samlet.
Professor og meditasjonsgrunnlegger Are Holen kommer med mange innsiktsfulle kommentarer og bidrar sterkt med sine refleksjoner og råd rundt stress. Men Holen er spredt flere steder gjennom boken.
Men bevares, «Stress. Og korleis leve med det» har i seg mange gode observasjoner og mye å lære bort, om å leve med stress.
Det er en liten bok, lett å lese, og de fleste vil utvilsomt finne noe «som passer for meg» her. Boken er inndelt i tre deler, om livet ditt, om kroppen din og om verdenen din, verken mer eller mindre. Og det er oppsummeringer med fine punkter om hvordan håndtere og leve med stre

Example 5889 (score: 0.9878):
LÅT: POP
Madonna (med Maluma)
«Medellín»
(Live Nation/Interscope)
«I took a pill and had a dream, I went back to my 17th year», er åpningslinjene på denne forløperen til Madonnas fjortende album.
Eller Madame X, som hun nå også kaller seg.
Det må man uansett kunne kalle en grei reise i tid: Hun runder faktisk 61 i august.
Altså nesten ti år eldre enn Cher var da hun opplevdes som hauggammel og hadde sitt siste store øyeblikk med «Believe» i 1998. Samme år som Madonna selv ga ut karrieretoppen «Ray of Light». Og året før Enrique Iglesias gjorde latinopopen en kanskje ikke like stor tjeneste med «The Rythm Divine».
Disse opplysningene er på forskjellig vis med å utgjøre «Medellín». Den har en tendens til å henfalle mot sistnevnte i avrundingen. Og nipper til førstnevntes hang til autotune innimellom. Samtidig er begge deler åpenbare grep som trekker mot William Orbit-klangene Madonna gjorde til allemannseie i 1998.
Solide historiske referanser, altså.
Flere skal bli.
Men først hovedpersonen: Her får colombianske Maluma (25), en superstjerne som for tiden skinner mye sterkere enn Madonna, lov til beholde mikrofonen i store deler av låten. Dette Despacito-grepet gjør at denne Madame X ikke fremstår som en aldrende tante med aldershjemsfobi, men heller en mystisk og udefinerbar skapning.
Produsenten Mirwais, franskmannen som gjorde «Music» (2000) så nydelig frisk og fremoverlent har funnet tilbake til sin egen kjerne. Han skrur som om han også var 17. Eller så har tiden innhentet både ham og Madonna, og begge egentlig har vært så forut for sin tid at vi ikke helt kan fatte det. Reggaeton-rytmene i bunnen går egentlig helt tilbake til «La Isla Bonita» (1986).
Nok en gang har denne forunderlig endringssøkende popartisten klart å redefinere seg selv. Uten å rote i EDM-faktene hun har vært litt for besnæret av de siste årene. Her er hun i stedet saktedansende sensuell og hviskende rytmisk. Så får det heller gå at Madonnas linjer er snublende, smått håpløse og balansert naive

Example 97374 (score: 0.9856):
Vignett: Konsert
Tittel:
Tekst: Arnfinn Bø-Rygg
Verker av Rameau, Mozart, Schubert og Anestis Logothetis.
Johannes Held, baryton, SSO, dir.: Simon Gaudens.
Stavanger konserthus, torsdag kveld
1 2 3 4 5 6
Jon Ingemundsen
Endelig fikk vi på årets første abonnementskonsert høre sanger – lieder – av Schubert, i en konsertserie som er viet stemmen. Schubert skapte denne sjangeren som vever det instrumentelle tett sammen med tekstene. De seks sangene som Johannes Held fremførte på en ganske overbevisende måte, var rimeligvis orkestreringer, i stedet for originalen som er for klaveret. Ikke alle orkestreringer er like vellykket, best klang Weberns bearbeidelse av «Du bist die Ruh». Den siste sangen, den kjente Erlkönig med tekst av Goethe, er også godt orkestrert av Max Reger. Men dette er en intenst dramatisk sang som Held ikke mestret i denne utgaven: Det ble ingen forskjell mellom farsstemmen og barnets stemme, som er selve nerven i sangen.
En latterlig mangel i presentasjonen av sangene var at sangtekstene bare forelå på engelsk i programfolderen. Det må ha vært forvirrende for dem som fulgte med her, verre enn ingen tekst vil jeg si. Erlkönig på engelsk!
Men kveldens første verk var det lille «Entrée de Muses» (Musenes inntog) fra Rameaus opera Les Boréades (1764). Det er et langsomt stykke med lange melodiske linjer som ble helt nydelig spilt av SSO.
Grafisk estetikk
Den gresk-østerrikske komponisten Anestis Logothetis (1921-1994) er kjent for sin personlige form for grafisk notasjon som gir hans verker en egenartet estetikk. Denne møter musikerne i verket som ble valgt torsdag, Polymeron, som utgjør en del av Himmelsmechanik (1960). I overensstemmelse med denne estetikken fikk vi en prøve på kombinasjonen av detaljrike musikalske ideer og de utøvendes medskapende utforming av disse. Og dirigenten, Simon Gaudens, hadde laget veien mellom de syv bildene som vi også så på lerretet og som ga assosiasjoner til stjernebilder.
Olympisk storhet
Kveldens hovedverk var Mozart

Example 32623 (score: 0.9845):
Aftenposten har en dyktig korrespondent i Sentral-Europa, som også trekker frem viktige historiske hendelser. Bra! Men fremstillingen av oppstanden i Warszawa 1944 i Aftenposten 2. august, er mangelfull.
Oppstanden faller i tid sammen med frigjøringen av Paris, det den franske motstandsbevegelsen og fremrykkende amerikanere koordinerte aksjonene. Paris ble befridd. Oppstanden i Warszawa startet 1. august, varte i 63 dager, sovjetstyrkene ved byen var passive. Etter å ha oppfordret til motstand mot tyskerne kalte Moskva Radio motstandskjemperne kjeltringer. Forsøk fra de vestallierte på å hjelpe, ble stoppet av Stalin. Mens polakkene ble slaktet, solbadet Den røde hær på andre siden av Wisla. Stalin ville ikke ha et fritt Polen, men et kommunistisk diktatur. En ny okkupasjon.
3rd-party-bio
Hele dette bakteppet er fraværende i korrespondentens ellers gode tekst. For øvrig ikke helt ulikt underkommuniseringen av kommunismens brutalitet i våre barns lærebøker.
Einar Kr. Steffenak, lektor
I skogbruket må vi prøve å forholde oss til utfordringen det er å forvalte naturen når den aller viktigste rammebetingelsen, nemlig klima, er i endring. Leder i Naturvernforbundets skogutvalg, Gjermund Andersen, har ikke dette perspektivet. Temperaturøkning forlenger vekstsesongen. Nye arter kommer av seg selv og arter vi har i dag vil flytte på seg. Naturens dynamikk har gjort at Norge har reetablert en vegetasjon etter istiden. Skal skogbruket bli uthengt for at man ikke tar hensyn hver gang en ny art oppdages eller noe endres?
I skogbruket merker vi oss at rødlistede arter synes å «dukke opp» på svært mange steder, bare man leter. Er rødlisten relevant eller er den egentlig et symbol på manglende oversikt, registreringer og kunnskap?
Dette bør være svært sentrale diskusjoner. Klima krever at skogen brukes. Skogen er et effektivt og ikke minst det billigste virkemiddel for økt binding av CO2. Andersen er imidlertid en av dem som bremser med begge bein.
Gudmund Nordtun, adm. dir., Glom

Example 100871 (score: 0.9833):
1 2 3 4 5 6
Haruki Murakami: Drapet på kommandanten Bok. Roman. 1 Oversatt fra japansk av Ika Kaminka og Yngve John Larsen. 408 sider. Pax.
Den som er bokanmelder, f.eks. i Aftenbladet, må sjølsagt våge å stole på egne vurderinger og komme med kritiske kommentarer, også om de gjelder japanske Haruki Murakami (f.1949), den bestselgende kultforfatteren som hyppig ble nevnt som kandidat til Nobelprisen i litteratur før metoo-kampanjen og intern personstrid førte til foreløpig kollaps for arbeidet til Svenska Akademien.
For første del av hans 14. roman, «Drapet på kommandanten», er ikke noe briljant mesterverk som bare innbyr til kritikerros. Teksten prater ofte for mye, utsier for lite, og den punkterer tidvis spenningen i historien på uheldig vis.
Det dreier seg om en tilbakeskuende jeg-fortelling der en navnløs, 36-årig portrettmaler fra Tokyo bretter ut livet sitt. Etter å ha blitt dumpet av kona Yuzu, en arkitekt som trolig skaffet seg en elsker og derfor ville ut av ekteskapet etter seks års samliv, leier han et avsidesliggende hus i det japanske innlandet. I dette rurale miljøet utspiller mesteparten av handlingen seg.
Noe av dramatikken i malerens liv knytter seg til det brutte ekteskapet. Men først på side 379 - etter å ha bodd flere måneder alene, uten kontakt med Yuzu, henne han kaller sitt livs store kjærlighet - mottar han en rekommandert sending med skilsmissepapirene. Dersom du skulle være spent på hvordan det går videre etter at han fyller ut papirene og sender dem i retur, har fortelleren allerede røpet det på side 9. Et lite lurt komposisjonsgrep, spør noen meg.
Ellers innleder maleren som aldri var utro mens han var gift, snart et forhold til to gifte kvinner han møter mens han er tegnelærer på en lokal kulturskole, og i tillegg har han sporadisk, heftig sex med en kvinne han ikke kjenner. Enkelte av samleiescenene er såpass råe og frisinna i tonen, med mange tabuord, at de har en pornografisk klang. Særlig påfallende er malerens fetisjaktige fascinas

Example 102038 (score: 0.9799):
Sjanger: Komedie. Skuespillere: Seth Rogen, Charlize Theron, Alexander Skarsgård, Andy Serkis, O'Shea Jackson Jr., Randall Park. Regi: Jonathan Levine. Nasjonalitet: USA. Lengde: 2 t. 5 min. Aldersgrense: 12 år.
1 2 3 4 5 6
Ingen skal beskylde regissør Jonatahan Levine for å finne opp kruttet med «Long Shot». Det han imidlertid gjør, er å plassere kruttet på litt andre steder enn vi er vant til. Det gir filmen et forfriskende preg, selv om den i og for seg er forutsigbar nok.
Hovedpersonen er den rufsete, dyktige journalisten Fred, en mann med oppsiktsvekkende dårlig klessmak og betenkelige rus-vaner. Barnevakten hans da han var liten, Charlotte (Charlize Theron), er utenriksminister med president-ambisjoner. Hun er vakker, dyktig, engasjert og kalkulert. Når de ved en tilfeldighet møtes igjen i voksen alder, bestemmer hun seg for å ansette Fred som taleskriver, til sine nærmeste medarbeideres store fortvilelse.
Det skal godt gjøres å ikke gjette hva som skjer videre, men veien dit er krydret med rikelig med komiske situasjoner. Man kan muligens beskylde regissør Levine for å sette ting vel mye på spissen og presentere situasjoner som er i overkant usannsynlige, selv for en tøysete romantisk komedie. På den annen side vet vi jo en del om virkeligheten i Det hvite hus i dag, og den skal det som kjent litt til for å overgå.
Filmen benytter også anledningen til å si noe om hvordan kvinner måles og vurderes etter andre kriterier enn menn når de forsøker å nå den politiske toppen i USA. Dette vet vi jo egentlig, men det er greit at også lettbeint underholdning som dette kan minne oss om at kvinner blir oppfattet som hysteriske mens menn som oppfører seg på nøyaktig samme måte i samme situasjon blir omtalt som engasjerte. Heldigvis er både Theron og Rogen så overbevisende og sjarmerende i rollene sine at det aldri blir moraliserende og kleint. Og hvis vi skrur av kynismen, kan vi nesten tro på at de ville funnet hverandre i virkeligheten også.

Example 110740 (score: 0.9790):
1 2 3 4 5 6
Hilde Rød-Larsen: Sommertid. Roman. 215 sider. Aschehoug.
Ingrid 52 år og Peder 67 år vaknar til årets første varme sommardag i huset sitt på Nesøya utanfor Oslo. Peder har blitt pensjonist og Ingrid er journalist i Aftenposten. Dei har det ikkje bra saman. Ingrid er sur og Peder latar som ingenting; vartar opp Ingrid med serviettar og dill istaden for å banke neven i bordet og rope: Kvifor går du rundt og er så jævla bitsch? Det er kanskje ikkje slik godt vaksne menn frå fine familiar frå Nesøya ordlegg seg, og då hadde òg denne romanen vore ferdig før han hadde begynt. Korleis skal det gå med Peder og Ingrid denne dagen? Før Ingrid går på jobb lirer ho av seg: “Jeg orker ikke dette lenger.” Dette er jo ikkje bra, og eg blir jo forviten på korleis det kjem til å gå.
Boka vekslar mellom å fortelje dagen frå Ingrid og Peder sitt perspektiv, og me får nok av bakgrunnsinformasjon om dette paret. Ingrid er pen i svart finbukse på bussen i storleiken extra small. Ho er ei kjølig kvinne som endar opp med å skulke jobben og går på måfå rundt i byen i staden. Ho ser på folka med eit nedlatande, hoverande blikk. Ho er humørlaus og utan sjølvironi. Me kjem nær Ingrids kropp, men kanskje ikkje sinn? Til det er blikket for surt. Ho vandrar rundt på Grünerløkka med ei klasseforakt, ei forakt frå sin eigen bakgrunn?
Vi kjem tett på Ingrids kropp med presise og detaljrike skildringar. Peders kropp er meir diffus, han blir fortald meir frå eit ytre blikk. Peders forteljing kjem sterkare etterkvart, og det blir eg letta over, for Ingrid får lov til å dominere altfor mykje i starten av boka. Eg blir glad når Peder får meir plass i slutten av boka, her er forfattaren god til å setje Peder i ein setting som viser mykje av han kven han er, nemleg saman med barn, barnebarn og eks-kone. Det gjer dette til ein balansert roman.
For deg som vil ha litt lett parforhold-problematikk på tampen av ferien, så er “Sommertid” fin lesing. For meg blir denne boka meir ei opptakt til ei fo

Example 74706 (score: 0.9784):
eTV: Det er duket for første semifinale i «Eurovision». Vi tar for oss all bidragene som kjemper om en plass i lørdagens finale i Israel.
1. Kypros: Tamta - «Replay»
Tamta går bredt ut og har på ingen måte til hensikt å stupe ned i den tradisjonelle «Eurovision»-klisjésumpen. Det låter lekent, lett og moderne. Og ganske fengende, må det sies. Etno-inspirert elektropop ligger på bordet og den unge sangeren serverer måltid med bøtter av selvtillit og glimt i øyet.
Er det her nivået i årets «Eurovision» skal ligge?
2. Montenegro: D-moll - «Heaven»
Det var nesten som om man ble litt optimistisk i noen sekunder der. Montenegro sørger for å dra det hele ned på bakkenivå igjen med sur møljesang som ikke har så mye annet å by på enn et repetivt gladpop-refreng som ikke går noen steder.
Det smiler det de er gode for og den tallrike gjengen har pyntet seg fint, men jeg tviler på det tar dem langt i denne konkurransen.
3. Finland: Ville Darude Virtanen - «Look Away»
Finland satser på temposterk elektropop med dype dynamiske daler som tidvis skjeler kraftig i retning Kim Wilds «You Keep Me Hanging On». Virtanen ser tent ut med tredagersskjegg og skinnjakke, men han er ikke like stødig vokalt. Det surner litt mellom slagene.
Men, men - slettes ikke det verste noen har prestert i denne konkurransen, men det blir nok heller ikke det mest minneverdige.
4. Polen: Tulia - «Fire of Love (Pali się)»
Det morsomme med «Eurovision» er at du av og til må tenke ganske hardt for i det hele tatt skjønne hva enkelte av artistene baler med eller forsøker å se. Polens bidrag fremstår nesten som en blanding av punk og alternativ pop, men det ser ut som om hovedpersonene forsøker å formidle noe helt annet.
Et bisart skue på sett og vis, men det vekker i alle fall noe i deg. Forundring, kanskje?
5. Slovenia: Zala Kralj & Gašper Šantl - «Sebi»
Knatre, knatre - kan noen stikke opp på scenen og vekke hun der Zala? Det ser jammen ut som om den søvndyssende og minimalistiske elektropopen får hovedperson

Example 84286 (score: 0.9782):
25. mai neste år inntar Nick Cave and The Bad Seeds Oslo Spektrum. Det melder arrangør All Things Live i en pressemelding.
Promotør Mark Vaughan hos All Things Live er strålende fornøyd med bookingen.
- Norge er storfans av Nick Cave. Alle de siste konsertene hans her har solgt ut i løpet av minutter, og hans siste album, «Ghosteen», er et av de beste albumene fra året så langt. Denne turneen tar Cave med seg sitt mest omfattende sceneshow så langt, og alle i Norge burde glede seg! sier han til Dagbladet.
«Ghosteen» er bandets syttende studioalbum, og har mottatt strålende anmeldelser i utlandet, blant annet fra The Guardian, som ga albumet fem av fem stjerner.
Her i Norge var mottakelsen mer lunken. Dagbladets anmelder trillet en treer på terningen, og skrev:
- Det er vakkert, og Cave synger med en sjelden innlevelse og glød. Men - det er også uvanlig stillestående. Det skjer veldig lite i sangene, som ofte består av lange, dvelende instrumentalpartier i tillegg til Caves milde stemme - sånn litt i Sigur Ros-land. Det føles uforløst.
Albumet er spilt inn i USA og Tyskland.
Det er ikke lenge siden sist artisten var i hovedstaden. I mai i år spilte han i Oslo Konserthus. Da var Dagbladets anmelder langt mer positiv, trillet en sekser og omtalte konserten som «tre magiske timer».
Som en del av konserten tok også artisten imot spørsmål fra salen.

In [ ]:
# check which source has the most positive/negative articles
sentiment_by_source = analysis_df.groupby("source")["label"].value_counts(normalize=True).unstack().fillna(0)
print("\nSentiment distribution by source:")
print(sentiment_by_source)

Sentiment distribution by source:
label   negative  neutral  positive
source
AA         0.006    0.787     0.207
AP         0.014    0.785     0.201
BT         0.029    0.669     0.302
DA         0.025    0.772     0.203
DB         0.038    0.733     0.229
DN         0.018    0.767     0.215
FV         0.003    0.691     0.306
NL         0.061    0.721     0.218
SA         0.022    0.712     0.266
VG         0.016    0.763     0.221

### *Fædrelandsvennen has the highest distribution of articles labeled as positive*
What are the top 3 positive articles from FV?

In [15]:
# print top 3 positive articles from FV
fv_positive = analysis_df[(analysis_df["source"] == "FV") & (analysis_df["label"] == "positive")].sort_values("score", ascending=False).head(3)
print("\n--- TOP 3 POSITIVE ARTICLES FROM FV ---")
for idx, row in fv_positive.iterrows():
    print(f"\nExample {idx} (score: {row['score']:.4f}):")
    print(row["text"][:2000])

--- TOP 3 POSITIVE ARTICLES FROM FV ---

Example 90578 (score: 0.9903):
Hei dere! Da er vi tilbake fra en sommer vi aldri kommer til å glemme, med oppsetningen ”Fruen fra havet” i Fjæreheia. Vi brukte noen uker både på å lande, og samle tankene etter så mange inntrykk. Det har vært en intens, lærerik, tøff, nydelig og utrolig verdifull prosess.
Vi visste lite om hva vi skulle forvente oss av det vi gikk inn i, bare at det krevde en god del vågemot og troen på at det er sunt å hoppe utfor hoppkanten av og til. Vi angrer ikke ett sekund. Vi er heller litt tomme for ord av takknemlighet og beundring over tilliten vi har fått. Vi tar hatten av for Birgit Amalie Nilssen. For ei rå dame du er! Vi følger nøye med, og tar inn så mye vi kan. Du er så varm og var. Det merkes av hele teamet, tror vi.
Privat
Det har vært mange dyktige mennesker å følge med på under denne reisen. Amalie Krogh i sitt ess, og Tove Kragset som en musikalsk påle – og ikke minst med evnen til å improvisere nye pianopartier hver eneste forestilling! Tenk å være så dyktig! Siste partiet hun spilte hver var mens vi sto bak scenen og ventet på finalen; vi sto og nøt med tårer i øynene. Noen har bare det lille ekstra.
Privat
Og stjernekoreografen Yabin Wang, med sine nydelige ”havdansere”. For et menneske, for en kunstner! Hun har en egen evne til å følge musikk etter følelsen. Det var helt unikt å følge hennes arbeidsprosess. Selv om hun ikke forsto tekstene vi hadde skrevet, skapte hun bevegelser som sto helt i tråd med uttrykket. Dette gjorde hun sammen med ”Den Fremmede” spilt av fantastiske Tomos Young. Vi hadde noen kjempegode samtaler om hva han opplevde at sangene sa, og han har en helt unik evne til å leve seg inn i dansen. Kunst krysser både landegrenser og sjangre.
Privat
Vi opplever at denne reisen viste oss hvordan kunst kan bygge broer. Man kan komme inn gjennom ulike dører til et felles møtepunkt hvor man skal yte etter beste evne, for å fortelle en historie. Tanken om å prestere på individnivå blir byttet ut med å gi seg hen til historien som et kollektiv. Man

Example 90260 (score: 0.9876):
BLOGG: Jeg har gått fra å være alt annet enn i form til det motsatte. Å komme i toppform handler om mange ting: Kondisjon, muskelstyrke, utholdenhet, kosthold osv. Og det å sette seg realistiske mål hele tiden. Egenvektstrening/calisthenics er min absolutte favoritt. Det gir stor mestringsfølelse og er like tungt som vanlig styrketrening.
I 2011 var jeg i skikkelig dårlig form og begynte å trene med en personlig trener. Jeg hadde trent litt på videregående skole på treningssenter, men uten særlig resultater. Under veiledning fra min PT gikk jeg i gang med generell styrketrening, med hovedfokus på kjernemuskulatur. Jeg trente tre ganger i uken, som med tiden har utviklet seg til at jeg nå trener seks-sju dager i uken. To til tre timer daglig. Jeg hadde personlig trener i to og et halvt år en gang i uken. Det gikk mye penger til dette, men det var absolutt verdt det. Jeg lærte utrolig mye om trening, kosthold og generelt hvordan kroppen fungerer. Det første halvåret gikk jeg ned ti kilo. Dette ga selvfølgelig mersmak. Noen av mine maks tester var da benpress 420kg, benkpress 110kg og pullups 20 stk.
Jeg fortsatte med treningen på egenhånd på treningsstudio i Kristiansand, der ble det mye styrketrening og en del løping. Da brukte jeg kettelbels og TRX (slynge), som også går mye på kjernemuskulatur. Jeg trente med egen kroppsvekt i tillegg som, push ups, dips, chins og pull ups. Passet også alltid på å få inn flere mageøvelser på treningsøktene. Etter hvert gikk fokuset over på løping, og da var målet å løpe det ti kilometer lange Sommerløpet på under 40 minutter. Tiden ble 40.52. Samtidig klarte jeg å holde styrketreningen vedlike. Da løp jeg fire dager, og hadde to styrkedager i uken.
KRSby.
I november 2014 begynte jeg med calisthenics. Jeg så på en plakat at Team Physix skulle ha workshop. Jeg sjekket på You Tube hva dette var, og syntes det nesten så umulig ut å gjennomføre noen av øvelsene. Jeg viste ikke om noen som skulle på kurset, men jeg hadde lyst til å prøve

Example 90119 (score: 0.9867):
SYNSPUNKT: Nyheten om at Kjetil Nordhus slutter som kreativ leder i Teateret med umiddelbar virkning kom som et sjokk for de fleste.
Vi er utrolig mange som sterkt beklager dette og føler at en stor forventning om en alternativ scene i Kristiansand nå faller i grus.
Etter gleden som lyste da selve bygningen ble reddet fra rivning og trusselen om å utbygge tomta til kontorer og leiligheten, ble fryden enda større da det ble klart at Teateret skulle bli et hus for kultur igjen. Da Kjetil Nordhus ble ansatt som kreativ leder på et tidlig stadium i planleggingsfasen, kunne begeistringen knapt bli større. For aldri kunne vel uttrykket rette mann på rette plass ha blitt brukt med så stor tydelighet.
Med sin tidligere erfaring som daglig leder for Sørf og med et kontaktnett innen de aller fleste kreative miljøer og kunstneriske uttrykk ville dette bli en fantastisk begynnelse på et eventyr om Teateret som et meget omfattende kulturhus for alle greiner av kulturens uttrykk. Musikk i alle former, teaterforestillinger for barn og voksne, litteratur og lyrikk, filosofi, spennende foredrag og mye mer skulle komme til uttrykk her i dette huset som skulle gjenoppstå som en fugl Fønix.
Og det gjorde det! Etter måneder med ombygging og planlegging hvor Kjetil Nordhus hadde kontor i Knas like rundt hjørnet og var lett å få kontakt med. Men etter at Teateret åpnet den 1. september 2018 var det nesten ikke en dag en så ham sitte i foajeen med sin Mac og hadde omtrent åpen kontortid for den som hadde forslag og ideer å lufte med ham.
Vil du skrive for Lokalkulturen?
Rune Stensland, Fædrelandsvennens produktsjef for Lokalkulturen, ønsker bidrag fra nye skribenter velkommen. Ta direkte kontakt med Rune på en av følgende:
Messenger
E-post
975 97 785
Teateret ble smakfullt innredet – med en foajé som innbød til aktivitet for dem som ønsket å kombinere en kopp kaffe med arbeid på nett. Og med en restaurant som tryllet fram spennende og velsmakende retter til en rimelig penge.
Intimscenen er

### *Nordlys has the highest distribution of articles labeled as negative*
What are the top 3 negative articles from NL?

In [16]:
# print top 3 negative articles from NL
nl_negative = analysis_df[(analysis_df["source"] == "NL") & (analysis_df["label"] == "negative")].sort_values("score", ascending=False).head(3)
print("\n--- TOP 3 NEGATIVE ARTICLES FROM NL ---")
for idx, row in nl_negative.iterrows():
    print(f"\nExample {idx} (score: {row['score']:.4f}):")
    print(row["text"][:2000])

--- TOP 3 NEGATIVE ARTICLES FROM NL ---

Example 94990 (score: 0.9665):
Mandag 19.august troppet 12 elever opp på Malangseidet skole, klar for et nytt skoleår. Både de og foreldrene var trygge på at de skulle få et år til på den nedleggingstruede skolen. Torsdag 22. august fikk vi melding om at skolen var blitt stengt med øyeblikkelig virkning. Tromsø brann og redning måtte stenge skolen pga. tekniske avvik som ikke var blitt rettet opp av Balsfjord kommune. Dette kom som lyn fra klar himmel på oss foreldre.
Hvordan i alle dager kunne dette skje uten at vi foreldre fikk noe informasjon? Administrasjonen fikk vite om dette november 2018. Jeg vil tro at de allerede i vår skjønte at de ikke ville klare å lukke avvikene før skolestart i høst. Burde de ikke da ha kalt inn til møte før sommerferien slik at elevene, foreldre, lærere og assistenter kunne forberedt seg på en skolestart på Sand skole. Elever har grått, foreldre har grått og lærere har grått. Det er så respektløs overfor dem og hele bygda at skolen ble stengt på denne måten. Kommunikasjon og informasjon – det er alfa og omega i de fleste sammenhenger. Her har det sviktet totalt i alle ledd.
26.august hadde vi foreldremøte sammen med ledelsen på skolen og representanter fra administrasjonen. Et møte hvor vi bare satt igjen med flere spørsmål enn svar, for ingen visste noen ting. Vi fikk vite at Malangseidet skole skulle fortsette som egen skole i nye lokaler ved Sand skole. Elevene skulle få minibuss og bli kjørt direkte til Sand for å slippe melkeruta som ungdomsskoleelevene har. Vi foreldre ønsket ikke at elevene skulle bli integrert i de andre klassene før formannskapsmøtet hadde vært 11.september. Bare noen få dager etter møtet fikk vi melding om at rådmannen hadde gitt en klar arbeidsordre om at elevene skulle integreres inn i Sand skole. Vi foreldre ble dermed ikke hørt. Etter at møtet med administrasjonen var ferdig, sa rektor at vi foreldre måtte fortsette møtet for å velge FAU. Da sier en fra administrasjonen: «Hvorfor skal dere velge FAU? Dere har jo ikke noe skole». Jo -

Example 94464 (score: 0.9572):
Hylekoret om at Nord-Norge-banen må forlenges fra Fauske til Tromsø har aldri vært sterkere enn nå. Oppildnet av de elendige meningsmålingene til Ap og den voldsomme veksten til Sp, ser politikere og debattanter i nord en mulighet til å presse en Jonas Gahr Støre til å gi grønt lys for baneforlengelse mens han er punch drunk.
Kravet fra nord er unisont: Hopp over alle utredninger, sett spaden i jorda. Og gjør det nå! Med voldsom utestemme hevdes det at journalister, forskere, pengeflyttere, sosialøkonomer, byråkrater og politikere i Oslo har gått sammen i en elitistisk, nedstøvet allianse. Alliansen ser ikke muligheten i den storslagne framtida for Nord-Norge. I havet, i mærene, i malmen i fjellene, i at flokken av turister som vil se nordlyset vil mangedobles.
Alliansen i sør har nesa si begravd i kjedelige, anemiske utredninger som gjør oss merkelig livsfjerne. For eliten i Oslo kjenner ikke det virkelige livet. Vi er polstret mot det gjennom alle pengene sinnrikt sluset mot Oslo fra fisk og olje. Vi lever et sedat caffelatte-liv fjernt fra det mytiske storhavet.
Og la det ikke herske noen tvil. Det virkelige livet utspiller seg i Nord-Norge. I et folk herdet gjennom århundrer gjennom den evinnelige kampen mellom mennesket og maktene. Nå er det Nord-Norges tur. Folket i nord er lei, de har satt sjøbein.
Og de står ikke med sydvesten og plirer mot vest og nord mot vågene ute på storhavet. De har satt øya i Oslo. Fordi vi fortjener det, gi oss pengene nå! Bruken av utestemme – demagogien og den dårlig skjulte hersketeknikken – klarer nesten å tildekke at gjengen fra nord driver et spill helt uten kalkulator.
Det er nemlig ikke slik at forlengelsen av jernbanen fra Fauske til Tromsø er et tvilsomt prosjekt. Det er grandiost samfunnsøkonomisk ulønnsomt. Forlengelsen av jernbanen vil ifølge Jernbanedirektoratet koste 130 – 150 milliarder kroner. Jernbanedirektoratet anslår at investeringen vil gi et tap for samfunnet på mellom 46 og 109 milliarder kroner.
Det er umulig

Example 93128 (score: 0.9434):
Debatten om vindkraft har tatt merkelige vendinger. Noen virkninger pumpes opp og blåses ut av proporsjoner, mens andre svært viktige sammenhenger oversees totalt. En del motstandere av vindkraft er så ensporete at de ikke evner å identifisere hva som truer naturmangfoldet.
Ved å vise til naturmangfoldsrapporten fra FN argumenters det med at nedbygging av naturen er farligere enn klimaendringene. FN har satt opp temaene på henholdsvis 1. og 3. plass. Å bruke lista til å isolere årsakene fra hverandre bidrar bare til å ufarliggjøre klimaendringene. Det tjener ingen på.
Det som bygger ned naturen er jordbrukets enorme monokulturer, vareproduksjon, byer og transportsystemer. Deretter bygges naturen ned på grunn av endringer i klima. Det siste er forårsaket av menneskenes mekanisering av nettopp jordbrukets enorme monokulturer, vareproduksjon, byer og transportsystemer.
De ensporete ser ikke dette, men har funnet ut at vindkraft er den store synderen. Enkelte går så langt som å hevde at naturen er skadet fra alle posisjoner en vindpark er synlig på en klar dag. Prøv noen kontrollspørsmål: «Er en kornåker ubrukelig fordi det er plassert en vindmølle på den?» Svaret er selvsagt nei. «Er et fjell ubrukelig som turområde fordi det står en vindpark der?» Nei igjen. Erfaringene fra Havøygaveln, Roan/Åfjord, Høgjæren og Lista viser at omkring 20 ganger flere går tur i området etter at der er bygd vindpark. Hvorfor? Jo, bilfrie veier egner seg flott til sykling, jogging og spaserturer. Folk flest liker tilrettelegging. Med slik effekt er vindparker gode folkehelsetiltak. Ikke rart at DNT føler at deres posisjon som tilretteleggere har fått konkurranse.
Det er en ærlig sak å være mot vindkraft, men da bør argumentasjonen være tilpasset årsaken til motstanden. Noen hevder at vi har strøm nok og at det ikke hjelper at lille Norge produserer mer. Disse har ikke forstått elementære fysiske lover og nekter å ta innover seg at Danmark har lagt ned flere kullkraftverk takket være overf

### *What author has the articles with the most negative/positive sentiment from each source?*

In [17]:
# find the most positive and most negative author from each source
most_positive_authors = (
	analysis_df[analysis_df["label"] == "positive"]
	.sort_values(["source", "score"], ascending=[True, False])
	.groupby("source", as_index=False)
	.head(1)
)

most_negative_authors = (
	analysis_df[analysis_df["label"] == "negative"]
	.sort_values(["source", "score"], ascending=[True, False])
	.groupby("source", as_index=False)
	.head(1)
)

print("\nAuthors with the most positive articles by source:")
print(most_positive_authors[["source", "author", "score"]])

print("\nAuthors with the most negative articles by source")
print(most_negative_authors[["source", "author", "score"]])

Authors with the most positive articles by source:
       source                               author     score
14194      AA                          Lars Sørnes  0.982586
40492      AP         Aftenpostens Musikkredaksjon  0.991355
43046      BT                          Ola Bernhus  0.985152
47705      DA                      Reidar Spigseth  0.994403
74333      DB                        Sofie Braseth  0.982366
66785      DN                    Jonas Christensen  0.950690
90578      FV                         Oakland Rain  0.990307
92636      NL                       Østen Mortvedt  0.952465
106841     SA                         Jan Askelund  0.993722
4776       VG  Camilla Norli, Gisle Oddstad (foto)  0.986848

Authors with the most negative articles by source
       source                                 author     score
14694      AA                                    NTB  0.813273
28368      AP                            Kenneth Moe  0.936094
44978      BT                 Eduardo Doddo Andersen  0.972139
53645      DA                     Jens Marius Sæther  0.894174
70410      DB                         Kjetil Rolness  0.892132
66913      DN                      Liv Kari Eskeland  0.960267
89526      FV  Pål Strande Gamlemoen,Anne-Marit Dahl  0.936311
94990      NL                         Maria S. Frost  0.966491
110838     SA                            Helge Kyvik  0.964816
509        VG                         Thomas Talseth  0.928576

In [18]:
most_positive_article = analysis_df[analysis_df["score"] == analysis_df["score"].max()].iloc[0]
most_negative_article = analysis_df[analysis_df["score"] == analysis_df["score"].min()].iloc[0]

for article in [most_positive_article, most_negative_article]:
    print("\n" + "="*80)
    print(f"Source: {article['source']}")
    print(f"Author: {article['author']}")
    print(f"Sentiment Score: {article['score']:.4f}")
    print(article["text"][:2000])

================================================================================
Source: DA
Author: Reidar Spigseth
Sentiment Score: 0.9944
TV-DRAMA
HBO Nordic, premiere mandag
Den første sesongen av «True Detective» var et sjeldent mørkt og rystende krimdrama, preget av en stille, søvnig og knugende stemning. Serien var rett og slett skummel, og hovedrollene var besatt av skuespillere Woody Harrelson og Matthew McConaughey, som var nærmest naturskapt for det gudsforlatte, gjengrodde Sørstats-Amerika de befant seg i. Handlingen ble fortalt i to tidsperioder, blant annet med eldre, slitnere Rust Cohle i samtale om fortidens drapsetterforskning. Rollen ga McConaughey status som karakterskuespiller for en stakket stund.
Dette var stor fortellerkunst, noir på en ny måte, en TV-krim et nivå over det meste i sin sjanger og TV-drama generelt. Her produserte HBO TV av ypperste kvalitet igjen! Serieskaper Nic Pizzolatto fikk ry som en fornyer og genial serieskaper. Alt skrytet forsvant med sesong to i antologien, en mørk, men mer tradisjonelt fortalt politiserie.
Serien handlet om flere politifolk i Los Angeles. Hele gjengen slet med rus og/eller familieproblemer, men som på hvert sitt vis oppdaget og bestemte seg for å bekjempe korrupsjon på høyt nivå i California. Intensiteten og nerven fra sesong én var erstattet med total desillusjonisme og dekadense. At støybunten Vince Vaughn spilte en krimboss som var litt god på bunnen, hevet ikke dramaet det spøtt. I amerikanske medier ble serien kjent som noe av det verste på TV i 2015. Etter fiaskoen skyldte HBO på at serieskaper Nic Pizzolatto var presset til å skrive en ny serie for raskt. Etter hvert fikk han likevel sjansen til å lage kapittel tre i detektiv-antologien sin.
Det er vel ikke rart Pizzolatto har gått tilbake til suksessformelen. Her benytter han mange av ingrediensene som gjorde sesong én til stort drama. Vi er tilbake i det gudsforlatte, fattige Sørstats-USA et sted. To politifolk etterforsker en fæl forbrytelse i en bister verden, atmosfæren er stille og dvelende, framdriften går sakte, og handlingen fortelles gjennom tre tidsperioder – i 1980, 199

================================================================================
Source: BT
Author: Dan Odfjell
Sentiment Score: 0.3580
Oppdatert for mindre enn 2 timer siden
Bakgrunn, red.anm.: Investor Dan Odfjell er blitt omtalt i flere artikler og innlegg i BT den siste tiden. Han er blant annet blitt kritisert for å ha gitt økonomisk støtte til partiet Alliansen og for å ha skrevet en rekke omstridte innlegg på nettstedet Resett. Teksten under er et tilsvar fra Odfjell.
Jeg ble sterkt forledet av partiet Alliansen ved dets formann og avsluttet enhver støtte til ham i løpet av ca. 15 dager, dvs. straks jeg forsto realitetene. Følgelig et mistak som dessverre kostet meg 250.000 kroner, ikke 500.000, slik BT skriver.
Jeg har ingenting til overs for Alliansen eller noe med dem å gjøre – eller slik BT utrolig frekt fremholder meg i Forum-saken. Dette synes meg faktisk bevisst sjofelt, og jeg forlanger herved en høyst tydelig straks-korreksjon fra BT.
Forøvrig har jeg aldri støttet Resett økonomisk, slik det også påstås (i innlegget «Derfor boikotter vi Forum» på bt.no 30. august, red.anm.). Men Resett publiserer noen av mine meningsytringer. Det er ytringsfrihet i Norge, og den gjelder også for dem som har meninger som ikke oppfattes av BT som politisk korrekte.
Et selskap, Ten Commandments, tilhørende min familie eier en minoritetspost i eiendomsselskapet som eier bygget der Forum Scene holder til. Jeg er ikke aktiv i dette eiendomsselskapet, jeg har ingen styreplass. Jeg har overhodet ingenting med Forum Scene å gjøre, og er selvsagt ikke involvert i driften av denne kulturarenaen.
Når det gjelder Verdidebatten som ble arrangert i Forum Scene 1. september, så har jeg heller ingenting med den å gjøre. Det er Salt-kirken som arrangerer den, og jeg er ikke invitert til å delta.
At noen partier ønsket å boikotte denne debatten fordi familien min eier aksjer i bygningen der debatten ble avholdt, er intet mindre enn absurd.

---
### *Topics and Text Sentiment*

In [19]:
model_name = "NbAiLab/nb-sbert-base"
embedding_model = SentenceTransformer(model_name, trust_remote_code=True)

model_dir = Path("../bertopic_models/NbAiLab_nb-sbert-base/NbAiLab_nb-sbert-base_ngram1-3_n50000_min_df10_20260409_201329").resolve()
topic_model = BERTopic.load(str(model_dir), embedding_model=embedding_model)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 1614.15it/s]
BertModel LOAD REPORT from: NbAiLab/nb-sbert-base
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [20]:
docs = analysis_df["text"].tolist()

topics, _ = topic_model.transform(docs)

Batches: 100%|██████████| 313/313 [15:48<00:00,  3.03s/it]
2026-04-29 17:26:35,757 - BERTopic - Predicting topic assignments through cosine similarity of topic and document embeddings.

In [21]:
# print all topics with their top 10 words except for topic -1 (outliers)
for topic in topic_model.get_topics().keys():
    if topic != -1:
        print(f"Topic {topic}: {', '.join([word for word, _ in topic_model.get_topic(topic)[:10]])}")

Topic 0: scoret, league, spillerne, spillere, champions, ballen, kamper, manchester, laget, sesong
Topic 1: brexit, parlamentet, statsministeren, statsminister, stortinget, regjering, valget, regjeringen, valg, avtalen
Topic 2: pågrepet, etterforskningen, drept, døde, fornærmede, politidistrikt, politiets, politiet, elisabeth, død
Topic 3: ulykken, nødetatene, politiet på, operasjonsleder, brannvesenet, politiet, politidistrikt, kjørte, brannen, hendelsen
Topic 4: årets, serien, tv, kjent, åringen, på, gang, filmen, fjor, film
Topic 5: president donald trump, presidentens, sa trump, presidenten, usas president, donald trump, president donald, trump, president, trumps
Topic 6: milliarder kroner, millioner kroner, kvartal, økte, veksten, milliarder, prisene, fjor, vekst, utviklingen
Topic 7: hunder, hund, dyrene, hunden, dyr, smittet, sykdommen, ulv, syke, diaré
Topic 8: meteorologisk, nedbør, meteorologisk institutt, stormen, været, regn, vind, varmere, vær, meldt
Topic 9: bompenger, elbiler, bilistene, elbil, samferdselsminister, statens vegvesen, biler, bilene, betale, millioner kroner
Topic 10: boligen, bygget, leiligheten, brannen, huset, eiendommen, bygg, kunstnere, blokken, eiendom
Topic 11: demonstrantene, demonstranter, protestene, demonstrasjonene, protester, opposisjonen, pågrepet, demonstrasjonen, sammenstøt, demonstrasjoner
Topic 12: klimakrisen, klimaendringene, klimaendringer, utslippene, utslipp, fornybar energi, 2030, co2, fornybar, gass
Topic 13: barnet, barn, barna, unge, første, julen, jul, veldig, livet, gang
Topic 14: jernbane nord, jernbanen, jernbane, nordnorsk, nord norge, nordkapp, narvik, nord, utredningen, debatt
Topic 15: turismen, turistene, turister, reiseliv, syden, reiser, besøkende, reise, byr på, migranter
Topic 16: satellitter, månen, planet, planeten, space, stjerner, universet, ferden, sendingen, milliarder
Topic 17: forskere, forskningen, vitenskap, forskerne, aftenpostens, forskning, artikler, bakterier, viten, funn
Topic 18: oljeselskapet, equinors, equinor, olje gass, norsk sokkel, offshore, på feltet, gass, olje, feltet

In [22]:
analysis_df["topic"] = topics
analysis_df.head(3)

,file,url,source,date,author,gender,class1,class2,language,title,...,text,word_count,sentence_count,verb_ratio,subject_ratio,passive_ratio,passive_of_verbs,label,score,topic
5643,VG-20190423-ekstra-bladet-danske.xml,http://www.vg.no/nyheter/utenriks/i/awOaE7/eks...,VG,2019-04-23 12:57,"Ingvill Dybfest Dahl, Ingeborg Huse Amundsen, ...",Female,"nyheter,utenriks",None,Bokmål,Ekstra Bladet: Danske Anders Holch Povlsen på ...,...,"Det skriver danske Ekstra Bladet, som siterer ...",439,27,0.099804,0.088063,0.007828,0.078431,neutral,0.540266,2
6808,VG-20190516-sarah-jessica-parker.xml,http://www.vg.no/rampelys/film/i/rA5exK/sarah-...,VG,2019-05-16 07:37,Catherine Gonsholt Ighanian,Female,"rampelys,film",None,Bokmål,Sarah Jessica Parker raser mot ukeblad – viser...,...,Den tidligere «Sex og singelliv»-stjernen har ...,435,26,0.095785,0.086207,0.001916,0.020000,neutral,0.640248,4
4593,VG-20190401-rotteracet-om-champi.xml,http://www.vg.no/sport/fotball/i/opEPLm/rotter...,VG,2019-04-01 10:20,Ole Kristian Strøm,Male,"sport,fotball",None,Bokmål,Rotteracet om Champions League-plass: – Det er...,...,Mandagens oddstips finner du her\n– Jeg våger ...,611,45,0.098571,0.092857,0.004286,0.043478,neutral,0.488746,0

---
### *Combining topics, sentiment and linguistics*

In [23]:
display_topic = 4
display_label = "negative"

sentiment_topic_selected = (
    analysis_df[analysis_df["topic"] == display_topic]["label"].value_counts()
)

selected_topic_df = analysis_df[analysis_df["topic"] == display_topic]
female_author_count = selected_topic_df[selected_topic_df["gender"] == "Female"].shape[0]
male_author_count = selected_topic_df[selected_topic_df["gender"] == "Male"].shape[0]
unknown_author_count = selected_topic_df[selected_topic_df["gender"] == "Unknown"].shape[0]

print(f"Total author distribution in topic {display_topic}:")
print(f"Female authors: {female_author_count}")
print(f"Male authors: {male_author_count}")
print(f"Unknown authors: {unknown_author_count}")

# print how many female/male/unknown authors have the selected sentiment in the selected topic
gender_counts = selected_topic_df[
    (selected_topic_df["label"] == display_label)
]["gender"].value_counts(dropna=False)
female_authors = int(gender_counts.get("Female", 0))
male_authors = int(gender_counts.get("Male", 0))
unknown_authors = int(gender_counts.get("Unknown", 0))

print(f"\nGender distribution in topic {display_topic} with {display_label} sentiment:")
print(f"Female authors: {female_authors}")
print(f"Male authors: {male_authors}")
print(f"Unknown authors: {unknown_authors}")

print(f"\nSentiment distribution in topic {display_topic}:")
for label, count in sentiment_topic_selected.items():
    print(f"{label}: {count}")

print(f"\nTop 10 articles with {display_label} sentiment score in topic {display_topic}:")

for _, row in selected_topic_df[selected_topic_df["label"] == display_label].sort_values("score", ascending=False).head(5).iterrows():
    print(f"Title: {row['title']}, Source: {row['source']}, Author: {row['author']}, Score: {row['score']:.4f}")
    print(f"Text preview: {row['text'][:500]}")
    print("-" * 80)

Total author distribution in topic 4:
Female authors: 216
Male authors: 318
Unknown authors: 123

Gender distribution in topic 4 with negative sentiment:
Female authors: 4
Male authors: 11
Unknown authors: 2

Sentiment distribution in topic 4:
neutral: 381
positive: 259
negative: 17

Top 10 articles with negative sentiment score in topic 4:
Title: Hetset Northug og Klæbo – nå anklager han NRK for løftebrudd, Source: FV, Author: Pål Strande Gamlemoen,Anne-Marit Dahl, Score: 0.9363
Text preview: SEEFELD/OSLO: Halfvarsson har sammen med NRK og humorprogrammet Helt Ramm laget en rapvideo med tittelen «Who the fuck is Norway?»
Halfvarsson innleder videoen med å sage hodet av en pappfigur av Johannes Høsflot Klæbo. Han harselerer også med Petter Northugs fyllekjøring:
«Du kræsjet karrieren din som du kræsjet bilen din,» rapper den svenske skiløperen.
Martin Johnsrud Sundby og Norge som land får også høre det i videoen.
LES OGSÅ: Carragher innrømmer gigantisk feilvurdering: – En åpenbaring u
--------------------------------------------------------------------------------
Title: Bokanmeldelse: Hva er poenget, Knut Nærum?, Source: AP, Author: Kenneth Moe, Score: 0.9361
Text preview: Ingen kan bestride at Knut Nærum er morsom. I alle fall skal ikke jeg gjøre det. Spørsmålet er hvor morsomt det er å lese 240 sider med syltynne krimfortellinger, som utelukkende er et stativ for vitsene hans.
Krimparodien Kyss meg, Døden omhandler 10 absurde saker etterforsket av privatdetektiv og tidligere ungdomsskolelærer Dreng Drabløs. Sakene henger mer og mer sammen etter hvert som den sløvsinnene helten oppdager sin egen rolle. Mange små konspirasjoner gjør til slutt én stor, med Drabløs
--------------------------------------------------------------------------------
Title: Raser mot ny Michael Jackson-dokumentar, Source: VG, Author: Thomas Talseth, Score: 0.9286
Text preview: Denne måneden får dokumentarfilmen «Leaving Neverland» premiere på Sundance-festivalen.
Filmens synopsis lover «opprivende intervjuer» med de nå voksne mennene og deres familier, og skal etter eget utsagn vise hvordan en aktet kunstner kan utnytte sin kjendismakt overfor «starstruck» barn og deres foreldre.
Boet etter Michael Jackson har kommet med en uttalelse om filmen til TMZ .
– Dette er nok en uhyggelig produksjon i et vanvittig og patetisk forsøk på å utnytte og tjene penger på Michael Jac
--------------------------------------------------------------------------------
Title: Måtte framføre på nytt: - Det siste han ønsket, Source: DB, Author: Henriette Eilertsen, Miriam Bakkejord, Marie Røssland, Score: 0.8736
Text preview: OSLO SPEKTRUM (Dagbladet): Da Melodi Grand Prix omsider var i gang, og Erlend Bratland (27) skulle i ilden, uteble nettopp ilden, altså pyro-effekter, som opprinnelig skulle være en del av sceneshowet.
Dette skyldtes ikke ulykken i forveien, der han endte opp med en brannskadd hånd, men var derimot en teknisk glipp.
Bratland måtte derfor framføre på nytt. Det bekrefter NRK overfor Dagbladet. Bratlands manager, Erland Bakke, er ikke fornøyd.
- NRK har bedt om at han skal gjøre låten sin enda en g
--------------------------------------------------------------------------------
Title: Filmanmeldelse «Destroyer»: Nicole Kidman i ikke spesielt pen-sjokk!, Source: VG, Author: Morten Ståle Nilsen, Score: 0.8707
Text preview: THRILLER/DRAMA
«Destroyer»
USA. 15 år. Regi: Karyn Kusama.
Med: Nicole Kidman, Sebastian Stan, Scoot McNairy.
Det er nesten blitt en egen sjanger. «Vi de-glamoriserer en av verdens vakreste kvinner og vinner Oscar fordi vi er så fryktløse Charlize Theron i « Monster » (2003) og – ja visst – Nicole Kidman som Virginia Woolf i « The Hours » (2002).
Det blir i alle fall publisitet av det. Vi er ikke bedre mennesker enn at vi elsker å se vakre personer i mindre heldig lys. Men når dette grepet blir
--------------------------------------------------------------------------------

---
### *Linguistic features*

In [24]:
selected_topic = 4
selected_topic_df = analysis_df[analysis_df["topic"] == selected_topic]

for source in selected_topic_df["source"].unique():
        print(f"\nLinguistic features for topic {selected_topic} by {source}:")
        print(f"Average subject ratio: {selected_topic_df[selected_topic_df['source'] == source]['subject_ratio'].mean():.4f}")
        print(f"Average passive ratio: {selected_topic_df[selected_topic_df['source'] == source]['passive_ratio'].mean():.4f}")
        print(f"Average verb ratio: {selected_topic_df[selected_topic_df['source'] == source]['verb_ratio'].mean():.4f}")
        print(f"Average passive per verb: {selected_topic_df[selected_topic_df['source'] == source]['passive_of_verbs'].mean():.4f}")

Linguistic features for topic 4 by VG:
Average subject ratio: 0.0910
Average passive ratio: 0.0039
Average verb ratio: 0.0986
Average passive per verb: 0.0419

Linguistic features for topic 4 by AA:
Average subject ratio: 0.0889
Average passive ratio: 0.0034
Average verb ratio: 0.1006
Average passive per verb: 0.0353

Linguistic features for topic 4 by AP:
Average subject ratio: 0.0857
Average passive ratio: 0.0045
Average verb ratio: 0.0940
Average passive per verb: 0.0476

Linguistic features for topic 4 by BT:
Average subject ratio: 0.0824
Average passive ratio: 0.0033
Average verb ratio: 0.0911
Average passive per verb: 0.0375

Linguistic features for topic 4 by DA:
Average subject ratio: 0.0931
Average passive ratio: 0.0041
Average verb ratio: 0.0994
Average passive per verb: 0.0423

Linguistic features for topic 4 by DN:
Average subject ratio: 0.0844
Average passive ratio: 0.0020
Average verb ratio: 0.0967
Average passive per verb: 0.0217

Linguistic features for topic 4 by DB:
Average subject ratio: 0.0909
Average passive ratio: 0.0039
Average verb ratio: 0.1003
Average passive per verb: 0.0403

Linguistic features for topic 4 by FV:
Average subject ratio: 0.0884
Average passive ratio: 0.0034
Average verb ratio: 0.0942
Average passive per verb: 0.0394

Linguistic features for topic 4 by NL:
Average subject ratio: 0.0880
Average passive ratio: 0.0040
Average verb ratio: 0.0937
Average passive per verb: 0.0443

Linguistic features for topic 4 by SA:
Average subject ratio: 0.0803
Average passive ratio: 0.0031
Average verb ratio: 0.0886
Average passive per verb: 0.0352

In [25]:
# print articles by AA in topic 16
aa_articles = analysis_df[(analysis_df["topic"] == 16) & (analysis_df["source"] == "NL")]
aa_articles = aa_articles[["title", "author", "source", "gender", "text", "verb_ratio", "subject_ratio", "passive_ratio", "passive_of_verbs", "topic"]]
aa_articles.head()

,title,author,source,gender,text,verb_ratio,subject_ratio,passive_ratio,passive_of_verbs,topic
93833,Naturvernforbundet – null troverdighet!,Tore Svendsen,NL,Male,Stortinget har vedtatt at Andøya Flystasjon sk...,0.111807,0.093023,0.005367,0.048000,16
95471,SAS tilbake med ny rute etter 12 års fravær,Are Medby,NL,Male,SAS kommer tilbake til Bardufoss - 12 år etter...,0.074074,0.080247,0.000000,0.000000,16
93340,Folke(helse)festen,Nordlys,NL,Unknown,Eventyret startet høsten 1989. Ideen om et mar...,0.102174,0.095652,0.004348,0.042553,16
92673,Nødraketter fra Gaza,Jarle Bakke,NL,Male,Mens Melodi Grand Prix forberedes med stor fes...,0.083333,0.085271,0.005814,0.069767,16
93904,Russisk militærfly skal overvåke i Nord-Norge,Pål Guttormsen,NL,Male,En russisk Antonov-maskin av typen An-30B skal...,0.133333,0.116667,0.008333,0.062500,16

In [26]:
# print full text from the first article by AA in topic 16
first_aa_article = aa_articles.iloc[3]
print(f"Text: {first_aa_article['text']}")
print(f"Verb Ratio: {first_aa_article['verb_ratio']:.4f}")
print(f"Subject Ratio: {first_aa_article['subject_ratio']:.4f}")
print(f"Passive Ratio: {first_aa_article['passive_ratio']:.4f}")
print(f"Passive per Verb: {first_aa_article['passive_of_verbs']:.4f}")

Text: Mens Melodi Grand Prix forberedes med stor festivitas i Israel, skytes primitive angreps-raketter opp fra Gazastripa. For de som kjenner palestinernes skjebne og lidelser under den israelske okkupasjonen, og virkningene av de store israelske militære bombeoffensiver fra 2007 og fram til i dag, kan oppskytingene moralsk betegnes som «nødraketter», med bønn til verden om hjelp.
Kontrasten mellom Midtøstens sterkeste militærmakt, Israel, med atomvåpen og USA som sin beste venn, og en utsultet og forpint befolkning som lever innesperret bak piggtråd, isolert fra omverden er et grovt brudd på elementære menneskerettigheter. At Israel ikke ser den historiske parallell til sin egen lidelseshistorie, vitner om hvor dypt avhumaniseringen er kommet og hvor umulig det er å lære av historien.
På Gazastripa, som er 36 km2, et område i utstrekning tilsvarende Målselvdalføret fra Øverbygd til Bardufoss, bor det 2 millioner mennesker. Halvparten av befolkningen er barn. Antallet drepte barn i første kvartal i år er 3 ganger så høy som i samme periode i fjor. 168 ubevæpnede palestinere, deriblant 22 barn ble drept og 1700 såret langs piggtrådsperringene av israelske soldater siden i mars. De fleste skutt i hode og bryst. I militære sammenheng oppfattes drapsraten som normal, og etter israelsk lov er drapene legale. Ingen straffeforfølges. Av hendelser i vår nære krigshistorie er det bare likegyldigheten til gettoene under 2.verdenskrig som Gaza kan sammenlignes med.
Under bombeoffensiven i 2014 ble 12000 boliger ødelagt, og under siste rakettutskytinger og påfølgende bomberaid, ble 130 hus ødelagt og 700 skadet. Israel oppfatter seg ikke som okkupant, så i deres øyne er de derfor fritatt ansvaret folkeretten pålegger landet som okkupant.
Den humanitære situasjonen på Gazastripen har ifølge FN blitt vesentlig forverret av Israels ekspansive okkupasjonspolitikk. FN varslet allerede i 2012 om at Gazastripa innen 2020 ville være ubeboelig for mennesker om ikke blokaden ble opphevet. Blokaden som Israel etablerte i 2007, har rasert grunnlaget for lokalt livsgrunnlag. Arbeidsledigheten er over 50% og folk er prisgitt gaver og hjelp fra giverland og FN for å overleve. Befolkningen lever under fattigdomsgrensen. De mangler strøm, drikkevann, helsevesen og utdanningssystem, og er i ferd med å miste sitt menneskeverd. Palestinerne på Gaza lever i fornedrelsens tid. Gaza er en getto, og lidelsene her aksepteres av israelerne med indoktrinert likegyldighet. At utsulting og blokade aksepteres også av norsk opinion og av våre politiske myndigheter, viser at vi tåler så vel den urett som ikke rammer oss selv.
Og mens FNs varslede katastrofe i Gaza-gettoen nærmer seg i tid, skytes nye raketter fra Gaza. De er nødrop fra to millioner mennesker innestengt bak piggtråd i et bur uten muligheter til flukt, mens vi nordmenn trekker likegyldig på skuldrene og skrur på Eurovisjons Melodi Grand Prix, for dette har vi jo vendt oss til, de er jo terrorister.
Verb Ratio: 0.0833
Subject Ratio: 0.0853
Passive Ratio: 0.0058
Passive per Verb: 0.0698